Replace FROM in Dockerfiles with real images (#2835)
* Pass --image to OpenShift build to override FROM

OpenShift (on cluster) build cannot cope with using "FROM $GO_RUNTIME"
in the Dockerfile and throws this error:
Create an image build for serverless-openshift-knative-operator
error: unable to locate any images in image streams, local docker images
with name "$GO_RUNTIME"

* Solution with replacing GO_RUNTIME from imageOverrides

* Read replacements directly from the orig Dockerfile

* Fixes

* Run make generated-files