Protect against status.conditions being null when installing operator
This will protect the installation against the following error:

06:50:04.827 DEBUG:   opentelemetry-operator.v0.93.0-3
opentelemetry-product openshift-operators : Waiting until non-zero (max
600 sec.)
subscription.operators.coreos.com/opentelemetry-product condition met
jq: error (at <stdin>:47): Cannot iterate over null (null)
06:50:33.495 ERROR:   🚨 Error (code: 5) occurred at
./hack/lib/tracing.bash:192, with command: subscription_error=$(oc get
subscription.operators.coreos.com "${subscription}" -n "${ns}" -ojson |
jq '.status.conditions[] | select(.message != null) |
select(.message|test("exists and is not referenced by a
subscription"))')
06:50:33.498 ERROR:   Stack trace:
06:50:33.500 ERROR:    1: ./hack/lib/tracing.bash:174
wait_for_csv_succeeded(...)
06:50:33.502 ERROR:    2: ./hack/lib/tracing.bash:142
install_operator(...)
06:50:33.505 ERROR:    3: ./hack/lib/tracing.bash:131
install_opentelemetry_operator(...)
06:50:33.507 ERROR:    4: ./hack/lib/tracing.bash:10
install_opentelemetry_tracing(...)
06:50:33.510 ERROR:    5: ./hack/tracing.sh:15 install_tracing(...)
make: *** [Makefile:135: operator-e2e] Error 5
{"component":"entrypoint","error":"wrapped process failed: exit status
2","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error
executing test
process","severity":"error","time":"2024-03-25T06:50:33Z"}
error: failed to execute wrapped command: exit status 2